export const LEGAL_DISCLAIMER = "DISCLAIMER: This application is a prototype simulation tool intended strictly for informational, educational, and testing purposes only. This app and its underlying mathematical models are completely independent and are neither supported, approved, nor sanctioned by the Central Provident Fund (CPF) Board or any government agency. All projections, calculations, and inferences generated by this tool are entirely hypothetical and should not be construed or relied upon as professional financial advice. The author(s) and creator(s) of this application shall not be held liable for any direct, indirect, incidental, consequential damages, losses, or legal repercussions arising from the use or misuse of this tool. Please consult a certified financial advisor before making any financial decisions.";

export const DEFAULT_INPUTS = {
  name: "", currentAge: 35, currentYear: 2026, payoutAge: 65,
  contributionStopAge: 65, housingStopAge: 55,
  isSelfEmployed: false, isMale: true, netTradeIncome: 0,
  oaBalance: 50000, saBalance: 40000, maBalance: 30000,
  showSalaryCalc: false, salaryGross: 6000, salaryBonus: 12000, salaryGrowthRate: 0,
  // Rev #22: phased salary & career break
  salaryPhaseAge: "", salaryGrowthRate2: 0,
  careerBreakStartAge: "", careerBreakEndAge: "",
  empOaCont: 12000, empSaCont: 4000, empMaCont: 4000,
  // VC3A: single cash lump-sum, auto-split by age-band allocation rates
  vc3aCash: 0,
  // RSTU: cash top-up to SA (pre-55) or RA (post-55)
  vcSaTopup: 0,
  // Housing refund: credited to OA (VHR)
  vcVhr: 0,
  // Gov grants / MRSS / MMSS / WIS
  annualGovGrant: 500,
  mrssGrant: 0,               // MRSS: govt matches RSTU RA top-up, up to $2,000/yr (lifetime cap $20,000), age 55+, RA below BRS
  mmssGrant: 0,               // MMSS: govt matches MA top-up, up to $1,000/yr, age 55-70
  wisAmount: 0,               // WIS: Workfare Income Supplement — 60% CPF (age-band), 40% cash (employees); 90% MA (SEP)
  // CPF Transfers
  oaToSaTransfer: 0,          // annual OA→SA transfer before 55
  oaToMaTransfer: 0,          // annual OA→MA transfer
  // Age 55 options
  oaWithdrawalAt55: 0,
  usePropertyPledge: false,
  pledgeWithdrawalAmount: 0,    // amount to withdraw from RA (pledged sum) as cash
  pledgeWithdrawalAge: 55,      // age at which member applies to withdraw pledged RA funds
  // CPFIS
  cpfisOaAmount: 0,    // Annual CPFIS investment from OA (OA must be > $20,000)
  cpfisSaAmount: 0,    // Annual CPFIS investment from SA (SA must be > $40,000, pre-55 only)
  // Outflows
  housingOutflow: 12000, oaEduLoan: 0, oaEduLoanFreq: 'one-time',
  medicalUsage: 500, medishieldIP: 900, elderCareShield: 500,
  medicalInflationRate: 5,
  propertyValue: 500000, propertyGrowthRate: 2, propertyLeasehold: false, propertyLeaseYears: 99,
  inflationRate: 2, includeProperty: true,
  sellPropertyAge: 0,
  // Private Assets & Goals
  targetMonthlyIncome: 0,
  currentPrivateAssets: 0,
  annualPrivateSaving: 0,
  privateAssetGrowthRate: 0,
  plannedDownpaymentOA: 0,
  downpaymentAge: 35,
  // OA Drawdown (post-payout-age supplementary income from OA)
  oaDrawdownStartAge: 0,         // 0 = disabled; age to begin drawing from OA (must be >= payoutAge)
  oaDrawdownMonthly: 0,          // monthly cash draw from OA (in addition to CPF LIFE)
  oaDrawdownFloor: 0,            // minimum OA balance to preserve (bequest floor); draw stops when OA hits this
  // Property Monetisation
  propMonetiseEnabled: false,    // master toggle
  propMonetiseScheme: "downgrade", // "downgrade" | "lbs" | "shb"
  propMonetiseAge: 65,           // age at which the scheme event occurs (one-time)
  propMonetiseCashProceeds: 0,   // net cash received by member (after CPF refund, stamp duty etc.)
  propMonetiseRaTopup: 0,        // RA top-up component (Silver Housing Bonus CPF portion, or LBS annuity lump-sum)
  // SRS (Supplementary Retirement Scheme)
  srsBalance: 0,
  srsAnnualContribution: 0,
  srsContribStopAge: 63,
  srsReturnRate: 4,
  srsDrawdownStartAge: 63,
  srsDrawdownYears: 10,
  // Die with Zero — fully deplete liquid assets by a target age
  dieWithZeroEnabled: false,
  dieWithZeroAge: 85,
  // Cash top-up to MA (direct, annual, any age, capped at BHS)
  vcMaCash: 0,
  // OA→MA transfer destination: false = self (internal move), true = loved one (OA outflow only)
  oaToMaForLovedOne: false,
  // OA→SA/RA transfer destination: false = self (internal move), true = loved one (OA outflow only)
  oaToSaForLovedOne: false,
  // Frequency toggles — 'annual' (recurring each year) or 'one-time' (applied in first year only)
  vc3aFreq: 'annual', vcSaFreq: 'annual', vcMaFreq: 'annual', vcVhrFreq: 'annual',
  govGrantFreq: 'annual', wisFreq: 'annual',
  cpfisOaFreq: 'annual', cpfisSaFreq: 'annual', housingFreq: 'annual',
  oaWithdrawalFreq: 'one-time', oaToMaFreq: 'annual', oaToSaFreq: 'annual',
  // Duration for recurring fields (0 = indefinite/∞; N = apply for first N projection years from current age).
  // Ignored when the paired *Freq is 'one-time' — one-time fields already fire only in year 1.
  // SRS excluded — its stop is controlled precisely by srsContribStopAge instead.
  vc3aDur: 0, vcSaDur: 0, vcMaDur: 0, vcVhrDur: 0,
  govGrantDur: 0, wisDur: 0,
  cpfisOaDur: 0, cpfisSaDur: 0, housingDur: 0,
  oaToMaDur: 0, oaToSaDur: 0, oaEduLoanDur: 0,
  // PR tenure year — 1, 2, or 3+ (3 = full rates). Only shown/relevant when citizenStatus === 'PR'.
  prYear: 3,
  // PR rate type — 'GG' (Graduated Employer + Graduated Employee, default) or
  // 'FG' (Full Employer + Graduated Employee, requires voluntary joint application).
  // Only applies when citizenStatus === 'PR' && prYear < 3. Year 3+ always uses full SC/PR3+ rates.
  prRateType: 'GG',
  // Global citizenship status: 'SC' (Singapore Citizen) or 'PR' (Permanent Resident).
  // Gates MRSS, MMSS (SC only), and PR tenure contribution warnings.
  // Foreigners are not modelled — they have no CPF entitlements.
  citizenStatus: 'SC',
  // Person with Disabilities (PwD): unlocks MRSS eligibility below age 55.
  // PwD members with OA+SA below BRS qualify for MRSS from 2026 regardless of age.
  isPwD: false,
  // Rev #5: Annual growth rate assumed for CPF retirement sums (FRS/BHS/BRS/ERS) projections.
  // CPF Board has historically raised these at ~3%/yr. Range: 0–10%; warn outside 0–6%.
  // Affects every projected FRS/BHS/BRS/ERS threshold in the engine and UI milestones.
  retirementSumGrowth: 3,
  // Rev #MC: Monte Carlo rate variance (±%). Controls the noise band applied to CPF interest
  // rates in each of the 200 simulation runs. Default 1% matches historical CPF rate stability.
  mcVariancePct: 1,
  // Rev #D2: Life Events — array of user-defined stress-test events overlaid on the projection.
  // Each event has: id, type, label, startAge, endAge, magnitude, enabled,
  // and optional type-specific fields: drawSource (medical_crisis), destination (windfall).
  lifeEvents: [],
  // ── RSS: Retirement Sum Scheme (pre-1958 members) ────────────────────────
  // cpfScheme: 'cpf_life' (default, born 1958 or after) | 'rss' (born before 1958).
  // Switching to 'rss' activates the runRSSEngine parallel path and shows the RSS tab.
  // All CPF LIFE logic, the LIFE tab, and runProjectionEngine are untouched.
  cpfScheme: 'cpf_life',
  // rssPayoutStartAge: age when CPF Board began RSS monthly drawdown (≥55, ≤currentAge).
  rssPayoutStartAge: 65,
  // rssMonthlyPayout: fixed monthly RSS payout amount as per CPF statement ($/month).
  rssMonthlyPayout: 0,
  // lifeMigrationAge: age to voluntarily migrate from RSS to CPF LIFE (0 = no migration).
  // lifePlanAtMigration: CPF LIFE plan chosen at the point of migration.
  //   'std' = Standard (fixed payout for life — CPF Board default)
  //   'esc' = Escalating (starts ~20% lower, rises 2%/yr — best long-run value)
  //   'bas' = Basic (lowest payout; RA retains a cash-refundable reserve)
  // Must be > currentAge and ≤ 80 (CPF policy deadline for migration).
  lifeMigrationAge: 0,
  lifePlanAtMigration: 'std',  // 'std' | 'esc' | 'bas' — CPF LIFE plan chosen at migration
};

export const PRESET_PROFILES = [
  {
    id: "blank", label: "Blank Slate", icon: "🧹",
    desc: "All zeros — start completely fresh",
    inputs: {
      name: "", currentAge: 30, currentYear: 2026, payoutAge: 65,
      contributionStopAge: 65, housingStopAge: 65,
      isMale: true, isSelfEmployed: false,
      citizenStatus: "SC", prYear: 3, prRateType: 'GG',
      oaBalance: 0, saBalance: 0, maBalance: 0,
      salaryGross: 0, salaryBonus: 0, salaryGrowthRate: 0,
      showSalaryCalc: false,
      empOaCont: 0, empSaCont: 0, empMaCont: 0,
      netTradeIncome: 0,
      vc3aCash: 0, vcSaTopup: 0, vcVhr: 0, vcMaCash: 0,
      annualGovGrant: 0, mrssGrant: 0, mmssGrant: 0, wisAmount: 0,
      oaToSaTransfer: 0, oaToMaTransfer: 0, oaToMaForLovedOne: false,
      cpfisOaAmount: 0, cpfisSaAmount: 0,
      housingOutflow: 0, medicalUsage: 0, medishieldIP: 0,
      elderCareShield: 0, medicalInflationRate: 0,
      propertyValue: 0, propertyGrowthRate: 0,
      includeProperty: false, propertyLeasehold: false, propertyLeaseYears: 99,
      sellPropertyAge: 0,
      oaWithdrawalAt55: 0,
      usePropertyPledge: false, pledgeWithdrawalAmount: 0, pledgeWithdrawalAge: 55,
      plannedDownpaymentOA: 0, downpaymentAge: 35,
      srsBalance: 0, srsAnnualContribution: 0, srsReturnRate: 0,
      srsContribStopAge: 63, srsDrawdownStartAge: 63, srsDrawdownYears: 10,
      currentPrivateAssets: 0, annualPrivateSaving: 0, privateAssetGrowthRate: 0,
      targetMonthlyIncome: 0,
      oaDrawdownMonthly: 0, oaDrawdownStartAge: 65, oaDrawdownFloor: 0,
      propMonetiseEnabled: false, propMonetiseCashProceeds: 0, propMonetiseRaTopup: 0,
      dieWithZeroEnabled: false, dieWithZeroAge: 85,
    }
  },
  {
    id: "typical35", label: "Typical Employee, 35", icon: "👔",
    desc: "Median CPF balances, $5.5k salary, HDB mortgage",
    inputs: { name: "Sample Member", currentAge: 35, payoutAge: 65, contributionStopAge: 65, housingStopAge: 55, isMale: true, oaBalance: 55000, saBalance: 35000, maBalance: 28000, salaryGross: 5500, salaryBonus: 11000, empOaCont: 12804, empSaCont: 4302, empMaCont: 4302, housingOutflow: 12000, medicalUsage: 500, medishieldIP: 900, elderCareShield: 500, propertyValue: 450000, propertyGrowthRate: 2, annualGovGrant: 500, targetMonthlyIncome: 3000 }
  },
  {
    id: "late50", label: "Late Starter, 50", icon: "⏰",
    desc: "Lower balances at 50, 5 years to SA closure",
    inputs: { name: "Late Starter", currentAge: 50, payoutAge: 65, contributionStopAge: 65, housingStopAge: 55, isMale: true, oaBalance: 80000, saBalance: 60000, maBalance: 55000, salaryGross: 6000, salaryBonus: 12000, empOaCont: 7920, empSaCont: 5160, empMaCont: 5160, housingOutflow: 8400, medicalUsage: 800, medishieldIP: 1200, elderCareShield: 600, propertyValue: 500000, propertyGrowthRate: 2, vcSaTopup: 8000, annualGovGrant: 500, oaToSaTransfer: 10000, targetMonthlyIncome: 3500,
      lifeEvents: [{ id: "le-late50-retrenched", type: "retrenchment", label: "Retrenchment", startAge: 52, endAge: 53, magnitude: 72000, enabled: true }] }
  },
  {
    id: "sep40", label: "Self-Employed, 40", icon: "💼",
    desc: "SEP mode, NTI $80k, no mandatory OA/SA",
    inputs: { name: "Freelancer", currentAge: 40, payoutAge: 65, contributionStopAge: 65, housingStopAge: 55, isSelfEmployed: true, isMale: true, netTradeIncome: 80000, oaBalance: 30000, saBalance: 25000, maBalance: 20000, empOaCont: 0, empSaCont: 0, empMaCont: 6720, vc3aCash: 20000, housingOutflow: 9600, medicalUsage: 500, medishieldIP: 900, elderCareShield: 500, propertyValue: 400000, propertyGrowthRate: 2, srsAnnualContribution: 15300, srsReturnRate: 4, srsContribStopAge: 63, srsDrawdownStartAge: 63, srsDrawdownYears: 10, targetMonthlyIncome: 3500 }
  },
  {
    id: "highearn40", label: "High Earner, 40", icon: "🚀",
    desc: "$8k salary cap, bonus at AW ceiling, ERS target",
    inputs: { name: "High Earner", currentAge: 40, payoutAge: 65, contributionStopAge: 65, housingStopAge: 55, isMale: true, oaBalance: 150000, saBalance: 120000, maBalance: 65000, salaryGross: 8000, salaryBonus: 6000, empOaCont: 14400, empSaCont: 5040, empMaCont: 5040, housingOutflow: 18000, medicalUsage: 600, medishieldIP: 1500, elderCareShield: 600, propertyValue: 1200000, propertyGrowthRate: 2, vcSaTopup: 8000, oaToSaTransfer: 20000, annualGovGrant: 0, srsAnnualContribution: 15300, srsBalance: 50000, srsReturnRate: 5, srsContribStopAge: 63, srsDrawdownStartAge: 63, srsDrawdownYears: 10, targetMonthlyIncome: 6000,
      lifeEvents: [{ id: "le-high40-medical", type: "medical_crisis", label: "Cancer Treatment", startAge: 60, endAge: 62, magnitude: 25000, enabled: true, drawSource: "oa_then_private" }] }
  },
  {
    id: "near55", label: "Near Retirement, 54", icon: "🔔",
    desc: "Age 54, near-FRS, focus on OA→SA + payout choice",
    inputs: { name: "Near Retirement", currentAge: 54, payoutAge: 65, contributionStopAge: 65, housingStopAge: 55, isMale: true, oaBalance: 180000, saBalance: 200000, maBalance: 72000, salaryGross: 7000, salaryBonus: 14000, empOaCont: 8400, empSaCont: 5520, empMaCont: 5520, housingOutflow: 6000, medicalUsage: 800, medishieldIP: 1500, elderCareShield: 600, propertyValue: 700000, propertyGrowthRate: 1.5, oaToSaTransfer: 15000, vcSaTopup: 8000, annualGovGrant: 500, targetMonthlyIncome: 4000 }
  },
  {
    id: "post55ra", label: "Post-55 RA Builder, 57", icon: "🏦",
    desc: "SA closed, RA below FRS — OA→RA + MRSS focus",
    inputs: { name: "RA Builder", currentAge: 57, payoutAge: 67, contributionStopAge: 65, housingStopAge: 57, isMale: true, oaBalance: 120000, saBalance: 90000, maBalance: 68000, salaryGross: 5000, salaryBonus: 10000, empOaCont: 6000, empSaCont: 3900, empMaCont: 3900, housingOutflow: 0, medicalUsage: 900, medishieldIP: 1600, elderCareShield: 600, propertyValue: 550000, propertyGrowthRate: 1.5, oaToSaTransfer: 12000, vcSaTopup: 8000, annualGovGrant: 500, targetMonthlyIncome: 3500 }
  },
  {
    id: "rss68", label: "RSS Member, 68", icon: "📋",
    desc: "Born before 1958 — RSS drawdown, exploring migration to CPF LIFE",
    inputs: {
      name: "RSS Member", currentAge: 68, currentYear: 2026,
      cpfScheme: 'rss', rssPayoutStartAge: 65, rssMonthlyPayout: 700, lifeMigrationAge: 0,
      oaBalance: 45000, saBalance: 158000, maBalance: 65000,
      contributionStopAge: 65, housingStopAge: 65,
      isMale: true, citizenStatus: 'SC',
      empOaCont: 0, empSaCont: 0, empMaCont: 0,
      medicalUsage: 1200, medishieldIP: 1800, elderCareShield: 600,
      propertyValue: 480000, propertyGrowthRate: 1,
      targetMonthlyIncome: 2500,
    }
  },
];

export const INPUT_LABELS = {
  name: "Name", currentAge: "Current Age", currentYear: "Current Year", payoutAge: "Payout Age",
  contributionStopAge: "Contrib Stop Age", housingStopAge: "Housing Stop Age",
  isMale: "Gender (Male)", netTradeIncome: "Net Trade Income", oaBalance: "OA Balance", saBalance: "SA Balance", maBalance: "MA Balance",
  salaryGross: "Gross Salary", salaryBonus: "Annual Bonus", salaryGrowthRate: "Salary Growth %",
  salaryPhaseAge: "Phase 2 Start Age", salaryGrowthRate2: "Phase 2 Growth %",
  careerBreakStartAge: "Career Break Start Age", careerBreakEndAge: "Career Break End Age",
  empOaCont: "Emp OA Contrib", empSaCont: "Emp SA Contrib", empMaCont: "Emp MA Contrib",
  vc3aCash: "VC3A Cash (Annual)", vcSaTopup: "RSTU SA/RA Top-up", vcVhr: "Housing Refund (VHR)",
  annualGovGrant: "Annual Gov Grant",
  wisAmount: "WIS (Workfare)", oaToSaTransfer: "OA→SA Transfer",
  oaToMaTransfer: "OA→MA Transfer", oaWithdrawalAt55: "OA Withdrawal at 55",
  usePropertyPledge: "Property Pledge", cpfisOaAmount: "CPFIS OA Invested", cpfisSaAmount: "CPFIS SA Invested",
  housingOutflow: "Housing Outflow", oaEduLoan: "OA Education Loan", oaEduLoanFreq: "OA Edu Loan Freq",
  medicalUsage: "Medical Usage",
  medishieldIP: "MediShield/IP", elderCareShield: "CareShield", medicalInflationRate: "Medical Infl. %",
  propertyValue: "Property Value", propertyGrowthRate: "Prop Growth %",
  propertyLeasehold: "Is Leasehold", propertyLeaseYears: "Lease Years",
  inflationRate: "Inflation Rate %", includeProperty: "Include Property",
  sellPropertyAge: "Sell Property Age",
  targetMonthlyIncome: "Target Monthly Income", currentPrivateAssets: "Private Assets",
  annualPrivateSaving: "Annual Private Saving", privateAssetGrowthRate: "Private Asset Growth %",
  plannedDownpaymentOA: "OA Downpayment", downpaymentAge: "Downpayment Age",
  oaDrawdownStartAge: "OA Drawdown Start Age", oaDrawdownMonthly: "OA Monthly Drawdown",
  oaDrawdownFloor: "OA Drawdown Floor", propMonetiseEnabled: "Prop Monetise",
  propMonetiseScheme: "Prop Scheme", propMonetiseAge: "Prop Monetise Age",
  propMonetiseCashProceeds: "Prop Cash Proceeds", propMonetiseRaTopup: "Prop RA Top-up",
  srsBalance: "SRS Balance", srsAnnualContribution: "SRS Annual Contrib",
  srsContribStopAge: "SRS Contrib Stop Age", srsReturnRate: "SRS Return Rate %",
  srsDrawdownStartAge: "SRS Drawdown Start Age", srsDrawdownYears: "SRS Drawdown Years",
  isSelfEmployed: "Self-Employed", showSalaryCalc: "Show Salary Calc",
  pledgeWithdrawalAmount: "Pledge Withdrawal Amount", pledgeWithdrawalAge: "Pledge Withdrawal Age",
  dieWithZeroEnabled: "Die with Zero", dieWithZeroAge: "Die with Zero Age",
  vcMaCash: "Cash Top-up to MA", oaToMaForLovedOne: "OA→MA For Loved One", oaToSaForLovedOne: "OA→SA/RA For Loved One",
  prYear: "PR Tenure Year", citizenStatus: "Citizenship Status", isPwD: "Person with Disabilities (PwD)",
  retirementSumGrowth: "Retirement Sum Growth (%/yr)",
  mcVariancePct: "Monte Carlo Variance (%)",
  lifeEvents: "Life Events",
  cpfScheme: "CPF Scheme", rssPayoutStartAge: "RSS Payout Start Age",
  rssMonthlyPayout: "RSS Monthly Payout ($)", lifeMigrationAge: "Migrate to CPF LIFE Age",
  lifePlanAtMigration: "CPF LIFE Plan at Migration",
  cpfisOaFreq: "CPFIS OA Freq", cpfisSaFreq: "CPFIS SA Freq",
  oaWithdrawalFreq: "OA Withdrawal Freq", oaToMaFreq: "OA→MA Freq", oaToSaFreq: "OA→SA Freq", prRateType: "PR Rate Type",
  vc3aDur: "VC3A Duration (yrs)", vcSaDur: "RSTU Duration (yrs)", vcMaDur: "VCMA Duration (yrs)",
  vcVhrDur: "VHR Duration (yrs)", govGrantDur: "Gov Grant Duration (yrs)",
  wisDur: "WIS Duration (yrs)",
  cpfisOaDur: "CPFIS OA Duration (yrs)", cpfisSaDur: "CPFIS SA Duration (yrs)",
  housingDur: "Housing Duration (yrs)", oaToMaDur: "OA-MA Duration (yrs)",
  oaToSaDur: "OA-SA Duration (yrs)", oaEduLoanDur: "OA Edu Loan Duration (yrs)",
};

// Alias used by the Compare tab — same labels, one source of truth
export const SCENARIO_LABELS = INPUT_LABELS;
